language: csharp
mono:
  - latest
  - 5.0.1

script:
  - msbuild /p:Configuration=Debug /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln /nowarn:MSB3277
  - msbuild /p:Configuration=Release /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln /nowarn:MSB3277
