osx_image: xcode8.3
language: csharp
solution: RealmExtensions/RealmExtensions.sln
install:
  - cd RealmExtensions
  - nuget restore RealmExtensions.sln
script:
  - cd RealmExtensions
  - msbuild /p:Configuration=Release RealmExtensions.sln
mono:
  - latest
  - 5.0.1.1
  - 4.8.1