# Main language/toolchain
language:
  - csharp

# Mono versions to test against
mono:
  - latest
  - 5.0.1

# Enable running inside a container (container-based infrastructure)
sudo:
  - false

# Default linux distro (Ubuntu 14.04)
dist:
  - trusty

# Global environment variables
env:
- MSBUILD_CONFIG="Debug"
- MSBUILD_CONFIG="Release"

# Build script
script:
  - msbuild /p:Configuration=${MSBUILD_CONFIG} /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln /nowarn:MSB3277
