language: csharp
solution: RealmExtensions/RealmExtensions.sln
mono:
  - latest
  - 5.0.1.1

install:
  - nuget update -this || true
  - nuget restore RealmExtensions/RealmExtensions.sln

before_script:
  - msbuild /version
  - nuget help | grep "Version"

script:
  - msbuild /p:Configuration=Release /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln
