osx_image: xcode8.3
language: csharp
mono:
  - latest
  - 5.0.1.1

before_install:
  - nuget | grep "Version"
install:
  - nuget restore RealmExtensions/RealmExtensions.sln

script:
  - msbuild /p:Configuration=Release /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln
