language: csharp
solution: RealmExtensions/RealmExtensions.sln
mono:
  - latest
  - 5.0.1.1

before_install:
  - msbuild /version || true
  - nuget help | grep "Version" || true
  - nuget update -this || true
  - nuget help | grep "Version" || true

install:
  - nuget restore RealmExtensions/RealmExtensions.sln

script:
  - msbuild /p:Configuration=Release /t:Restore,Rebuild RealmExtensions/RealmExtensions.sln
